[[main]]
  identifier = "about"
  name = "关于"
  url = "about"
  weight = 1

[[main]]
  identifier = "archive"
  name = "归档"
  url = "archive"
  weight = 2

[[main]]
  identifier = "tags"
  name = "标签"
  url = "tags"
  weight = 3

[[main]]
  identifier = "posts"
  name = "文章列表"
  url = "posts"
  weight = 4
